### ISSUE TITLE
Error when insertOne new data

### ISSUE THREAD

**Issue by WynnLin** [brickyang/egg-mongo-native#18]
Here is my config
`
exports.mongo = {
    client: {
      host: '127.0.0.1',
      port: '27017',
      name: 'test',
      user: 'root',
      password: 'root',
      options: {}
    }
  };
`
and I use it like `app.mongo.insertOne('name', '123123');`

for my mongoDB 
I have a database = test
in the test database i have a collection which named test also
![image](https://user-images.githubusercontent.com/26760434/45670864-7a67ba80-bb56-11e8-8ec8-b2d5f5ccd4ff.png)

the error is show when i call `app.mongo.insertOne('name', '123123');`
`2018-09-18 15:15:24,693 ERROR 44536 nodejs.TypeError: Cannot read property '_id' of undefined`

Is that clear for my issue

**Comment by brickyang** [comment]
`app.mongo.insertOne('test', { doc: { name: '123123' } })`
`app.mongo.find('test', { query: { name: '123123' } })`

**Comment by WynnLin** [comment]
> `app.mongo.insertOne('test', { doc: { name: '123123' } })`
> `app.mongo.find('test', { query: { name: 'test' } })`

sorry for my first use, so doc or query are keywords?

**Comment by brickyang** [comment]
https://github.com/brickyang/egg-mongo-native#example
