### ISSUE TITLE
feature request: support findAndModify

### ISSUE THREAD

**Issue by SilverLeaves** [brickyang/egg-mongo-native#23]
findAndModify 是一个特殊且有着无可替代功能的"原子操作"。

**Comment by brickyang** [comment]
欢迎 PR。否则我最早要到下周才能更新。

**Comment by SilverLeaves** [comment]
@brickyang 我现在还不会写测试！😭！提交一个没测试的PR可否？

**Comment by brickyang** [comment]
没有测试不行的。

**Comment by SilverLeaves** [comment]
@brickyang 我看了一下node的mongo包，里面的findOneAndUpdate之类的操作，内部竟然调用的是 findAndModify。
![default](https://user-images.githubusercontent.com/31165554/48815197-8cddba80-ed78-11e8-99a1-f9c5ed08c75d.png)

**Comment by brickyang** [comment]
是啊。` findAndModify` 的功能基本都可以被 `findOneAnd..` 类命令实现，而后者相对更安全一些。
