### ISSUE TITLE
transactions 事务支持

### ISSUE THREAD

**Issue by SilverLeaves** [brickyang/egg-mongo-native#27]
Mongo 4.X 开始支持 跨collection transactions 事务支持.
egg-mongo-native也支持一下呗。

**Comment by SilverLeaves** [comment]
或者把MongodbClient放出来，让事务功能可以用。

**Comment by SilverLeaves** [comment]
应该是每次`Startransaction()`每次返回一个`新 session`。

**Comment by SilverLeaves** [comment]
@brickyang 能不能暂时先给一个可以救急的东西先用着。

**Comment by brickyang** [comment]
我正在更新中，但是仍有细节需要考虑。

你可以先改本地源码？

**Comment by SilverLeaves** [comment]
@SilverLeaves 那我先不揭锅了༼ ∗ •̀ (oo) •́ ∗ ༽，你别着急

**Comment by brickyang** [comment]
先发小版本吧，增加一个 `startTransaction()`，返回 session 之后放在 collection 操作的 options 里，标准用法。

下一个大版本需要整体优化下 API。

**Comment by brickyang** [comment]
你可以试试 `npm i -S egg-mongo-native@next`。API 由 [easy-mongodb](https://github.com/brickyang/easy-mongodb) 提供。

**Comment by SilverLeaves** [comment]
给了两个方法，一个带参数，一个不带参数。。。
我直接用不带参的，没毛病吧
> startSession
> startTransaction

**Comment by brickyang** [comment]
`startTransaction()` 内部也是调用 `startSession()`，也返回 `session`。后者是以防需要 `session` 干别的。

你直接调用 `startSession()` 就自己再调用 `session.startTransaction()` 一下。

`startSession()` 也是（可以）有参数的，我记得应该补上了。

**Comment by brickyang** [comment]
下一步的计划是 `startTransaction()` 返回一个包装好的 `session`，在这个 `session` 上可以直接调用目前 `db` 的 API，不需要自己显示地使用 `options = { session }`。类似于：

```
const sess = app.mongo.startTransaction();
sess.insertOne(...);
sess.findOneAndUpdate(...);
sess.commitTransaction();
```

**Comment by SilverLeaves** [comment]
（〜^㉨^)〜棒呆，静候佳音

美滋滋٩(๑`н´๑)۶

我是伸手党༼ ∗ •̀ (oo) •́ ∗ ༽我喂你袋盐

**Comment by brickyang** [comment]
你实际用了吗？如果没 bug 就合了。
