### ISSUE TITLE
count 方法已被弃用

### ISSUE THREAD

**Issue by kasora** [brickyang/egg-mongo-native#30]
> DeprecationWarning: collection.count is deprecated, and will be removed in a future version. Use collection.countDocuments or collection.estimatedDocumentCount instead

是否考虑内部替换 `count` 方法，或者暴露 `countDocuments` 方法？

**Comment by kasora** [comment]
..不是版本的问题。是 `index.d.ts` 没有同步更新，里面只有 count 的接口描述。ts 用户就拿不到方法了。。
https://github.com/brickyang/egg-mongo-native/blob/master/index.d.ts#L117

**Comment by brickyang** [comment]
已经更新了，在等发新版。

**Comment by brickyang** [comment]
#31
