### ISSUE TITLE
agent 里可以用这个插件吗？？

### ISSUE THREAD

**Issue by tansuozhe123** [brickyang/egg-mongo-native#36]

**Comment by brickyang** [comment]
可以。

**Comment by tansuozhe123** [comment]
需要配置什么参数吗？？

**Comment by brickyang** [comment]
正常配置使用即可。

**Comment by tansuozhe123** [comment]
config.mongo = {
		client: {
			host: mongo_server_ip,
			port: '27017',
			name: 'example',
			user: 'gitxxxx',
			password: '123456',
			options: {
				useNewUrlParser: true
			},
		}
	};
这样配置，可以直接在agent通过agent.mongo直接使用吗?还是需要通过其他方式调用？？

**Comment by brickyang** [comment]
不好意思，只能通过 `app` 操作数据库连接实例。我看了下 `agent` 中好像是不能访问到 `app`，那么就不能使用插件。

p.s. 在 `agent` 中操作数据库是不建议的。

**Comment by tansuozhe123** [comment]
ok,非常感谢。
