### ISSUE TITLE
 请修改配置，支持URI模式

### ISSUE THREAD

**Issue by utoper-dev** [brickyang/egg-mongo-native#4]
config.mongo支持URI模式，如：
mongodb://user:password@localhost:27017/myproject
mongodb://localhost:27017,localhost:27018/myproject?replicaSet=foo

@brickyang

**Comment by brickyang** [comment]
这个似乎没有必要？

而且不太符合目前 egg.js 生态圈的习惯。

**Comment by utoper-dev** [comment]
我们的Mongo是集群的，就需要用到mongodb://localhost:27017,localhost:27018/myproject
支持两种配置方式，保留之前的options模式
或者我修改代码，提交给你合并？@brickyang
谢谢！

**Comment by brickyang** [comment]
@utoper-dev 

欢迎 PR

**Comment by brickyang** [comment]
[v2.1.0](https://github.com/brickyang/egg-mongo-native/releases/tag/v2.1.0)  released.
